version: '4.3'
services:
  master:
    image: cribl/cribl:latest
    environment:
      - CRIBL_DIST_MODE=master
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@0.0.0.0:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    ports:
      - "19000:9000"
    networks:
      - backbone
    volumes:
      - "~/cribl-config:/opt/cribl/config-volume"
  workers:
    image: cribl/cribl:latest
    depends_on: 
      - master
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@master:4200
    networks:
      - backbone
  ubuntu:
    image: ubuntu:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    ports:
      - "9001:9000"
    networks:
      - backbone
  nginx:
    image: nginx:alpine
    ports:
      - "5140:5140"
    networks:
      - backbone
    command: >
      sh -c "if [ ! -f /etc/nginx/stream.d/5140.conf ]; then
         apk add nginx-mod-stream &&
         mv /etc/nginx/conf.d/stream.conf /etc/nginx/stream.conf &&
         echo 'include /etc/nginx/stream.conf;' >> /etc/nginx/nginx.conf &&
         echo 'server {' > /etc/nginx/stream.d/5140.conf &&
         echo ' listen 5140;' >> /etc/nginx/stream.d/5140.conf &&
         echo ' proxy_pass 5140_tcp_backend;' >> /etc/nginx/stream.d/5140.conf &&
         echo '}' >> /etc/nginx/stream.d/5140.conf &&
         echo '' >> /etc/nginx/stream.d/5140.conf &&
         echo 'upstream 5140_tcp_backend {' >> /etc/nginx/stream.d/5140.conf &&
         echo ' least_conn;' >> /etc/nginx/stream.d/5140.conf &&
         echo ' server criblWithNginx-workers-1:5140;' >> /etc/nginx/stream.d/5140.conf &&
         echo ' server criblWithNginx-workers-2:5140;' >> /etc/nginx/stream.d/5140.conf &&
         echo '}' >> /etc/nginx/stream.d/5140.conf 
      fi &&
      rm -f /var/run/nginx.pid &&
      exec nginx -g 'daemon off;' -c /etc/nginx/nginx.conf"
networks:
  backbone:
    driver: bridge
